export * from './descaler/descaler.component';
export * from './downcoiler/downcoiler.component';
export * from './edger/edger.component';
export * from './intensive/intensive.component';
export * from './rolls-big/rolls-big.component';
export * from './rolls-small/rolls-small.component';
export * from './stand/stand.component';
export * from './trimming/trimming.component';
export * from './normal/normal.component';
